"""Type stubs for rtfkit."""

from typing import Optional, Sequence

__version__: str

# =============================================================================
# Exceptions
# =============================================================================

class RtfkitError(Exception):
    """Base exception for all rtfkit errors."""
    ...

class ParseError(RtfkitError):
    """RTF parsing failed."""
    ...

class ReportError(RtfkitError):
    """Report generation failed."""
    ...

class HtmlWriterError(RtfkitError):
    """HTML generation failed."""
    ...

class DocxWriterError(RtfkitError):
    """DOCX generation failed."""
    ...

class PdfRenderError(RtfkitError):
    """PDF rendering failed."""
    ...

# =============================================================================
# IR Types
# =============================================================================

class Color:
    @property
    def r(self) -> int: ...
    @property
    def g(self) -> int: ...
    @property
    def b(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Shading:
    @property
    def fill_color(self) -> Optional[Color]: ...
    @property
    def pattern_color(self) -> Optional[Color]: ...
    @property
    def pattern(self) -> Optional[str]: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Run:
    @property
    def text(self) -> str: ...
    @property
    def bold(self) -> bool: ...
    @property
    def italic(self) -> bool: ...
    @property
    def underline(self) -> bool: ...
    @property
    def font_family(self) -> Optional[str]: ...
    @property
    def font_size(self) -> Optional[float]: ...
    @property
    def color(self) -> Optional[Color]: ...
    @property
    def background_color(self) -> Optional[Color]: ...
    @property
    def inline_type(self) -> str: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Hyperlink:
    @property
    def url(self) -> str: ...
    @property
    def runs(self) -> list[Run]: ...
    @property
    def inline_type(self) -> str: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Paragraph:
    @property
    def alignment(self) -> str: ...
    @property
    def inlines(self) -> list[Run | Hyperlink]: ...
    @property
    def shading(self) -> Optional[Shading]: ...
    @property
    def block_type(self) -> str: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class ListItem:
    @property
    def level(self) -> int: ...
    @property
    def blocks(self) -> list[Paragraph | ListBlock | TableBlock | ImageBlock]: ...

class ListBlock:
    @property
    def list_id(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def items(self) -> list[ListItem]: ...
    @property
    def block_type(self) -> str: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class TableCell:
    @property
    def blocks(self) -> list[Paragraph | ListBlock | TableBlock | ImageBlock]: ...
    @property
    def width_twips(self) -> Optional[int]: ...
    @property
    def merge(self) -> Optional[str]: ...
    @property
    def merge_span(self) -> Optional[int]: ...
    @property
    def v_align(self) -> Optional[str]: ...
    @property
    def shading(self) -> Optional[Shading]: ...

class TableRow:
    @property
    def cells(self) -> list[TableCell]: ...
    def __len__(self) -> int: ...

class TableBlock:
    @property
    def rows(self) -> list[TableRow]: ...
    @property
    def block_type(self) -> str: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class ImageBlock:
    @property
    def format(self) -> str: ...
    @property
    def data(self) -> bytes: ...
    @property
    def width_twips(self) -> Optional[int]: ...
    @property
    def height_twips(self) -> Optional[int]: ...
    @property
    def block_type(self) -> str: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Document:
    @property
    def blocks(self) -> list[Paragraph | ListBlock | TableBlock | ImageBlock]: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

# =============================================================================
# Report Types
# =============================================================================

class Stats:
    @property
    def paragraph_count(self) -> int: ...
    @property
    def run_count(self) -> int: ...
    @property
    def bytes_processed(self) -> int: ...
    @property
    def duration_ms(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Warning:
    @property
    def warning_type(self) -> str: ...
    @property
    def severity(self) -> str: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

class Report:
    @property
    def warnings(self) -> list[Warning]: ...
    @property
    def stats(self) -> Stats: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> dict: ...
    def to_json(self, indent: Optional[int] = None) -> str: ...

# =============================================================================
# Limits
# =============================================================================

class ParserLimits:
    def __init__(
        self,
        *,
        max_input_bytes: Optional[int] = None,
        max_group_depth: Optional[int] = None,
        max_warning_count: Optional[int] = None,
        max_rows_per_table: Optional[int] = None,
        max_cells_per_row: Optional[int] = None,
        max_merge_span: Optional[int] = None,
        max_image_bytes_total: Optional[int] = None,
    ) -> None: ...
    @staticmethod
    def unlimited() -> ParserLimits: ...
    @property
    def max_input_bytes(self) -> int: ...
    @property
    def max_group_depth(self) -> int: ...
    @property
    def max_warning_count(self) -> int: ...
    @property
    def max_rows_per_table(self) -> int: ...
    @property
    def max_cells_per_row(self) -> int: ...
    @property
    def max_merge_span(self) -> int: ...
    @property
    def max_image_bytes_total(self) -> int: ...

# =============================================================================
# Parse
# =============================================================================

class ParseResult:
    @property
    def document(self) -> Document: ...
    @property
    def report(self) -> Report: ...

def parse(rtf: str) -> ParseResult: ...
def parse_with_limits(rtf: str, limits: ParserLimits) -> ParseResult: ...

# =============================================================================
# HTML
# =============================================================================

class HtmlOutput:
    @property
    def html(self) -> str: ...
    @property
    def dropped_content_reasons(self) -> list[str]: ...

def to_html(
    document: Document,
    *,
    emit_wrapper: Optional[bool] = None,
    css_mode: Optional[str] = None,
    style_profile: Optional[str] = None,
    custom_css: Optional[str] = None,
) -> str: ...

def to_html_with_warnings(
    document: Document,
    *,
    emit_wrapper: Optional[bool] = None,
    css_mode: Optional[str] = None,
    style_profile: Optional[str] = None,
    custom_css: Optional[str] = None,
) -> HtmlOutput: ...

# =============================================================================
# DOCX
# =============================================================================

def to_docx_bytes(document: Document) -> bytes: ...
def to_docx_file(document: Document, path: str) -> None: ...

# =============================================================================
# PDF
# =============================================================================

class PdfOutput:
    @property
    def pdf_bytes(self) -> bytes: ...
    @property
    def warnings(self) -> list[str]: ...

def to_pdf(
    document: Document,
    *,
    page_size: Optional[str] = None,
    margin_top: Optional[float] = None,
    margin_bottom: Optional[float] = None,
    margin_left: Optional[float] = None,
    margin_right: Optional[float] = None,
    style_profile: Optional[str] = None,
    fixed_timestamp: Optional[str] = None,
) -> bytes: ...

def to_pdf_with_warnings(
    document: Document,
    *,
    page_size: Optional[str] = None,
    margin_top: Optional[float] = None,
    margin_bottom: Optional[float] = None,
    margin_left: Optional[float] = None,
    margin_right: Optional[float] = None,
    style_profile: Optional[str] = None,
    fixed_timestamp: Optional[str] = None,
) -> PdfOutput: ...
